spring:
  application:
    name: scm-workshop
  sql:
    init:
      mode: always
  graphql:
    graphiql:
      enabled: true
  threads:
    virtual:
      enabled: true
logging:
  level:
    org:
      springframework:
        web: DEBUG